export enum AdminPermission {
    MEMBERS_READ = 'members:read',
    MEMBERS_WRITE = 'members:write',
    EVENTS_READ = 'events:read',
    EVENTS_WRITE = 'events:write',
    VENUES_READ = 'venues:read',
    VENUES_WRITE = 'venues:write',
    DEPARTMENTS_READ = 'departments:read',
    DEPARTMENTS_WRITE = 'departments:write',
    ATTENDANCE_READ = 'attendance:read',
    LEAVE_READ = 'leave:read',
    LEAVE_WRITE = 'leave:write',
    CLASSES_READ = 'classes:read',
    CLASSES_WRITE = 'classes:write',
    ANNOUNCEMENTS_READ = 'announcements:read',
    ANNOUNCEMENTS_WRITE = 'announcements:write',
    NOTES_READ = 'notes:read',
    NOTES_WRITE = 'notes:write',
    DASHBOARD_READ = 'dashboard:read',
    SUNDAY_SCHOOL_READ = 'sunday_school:read',
    SUNDAY_SCHOOL_WRITE = 'sunday_school:write',
    CHILDREN_CHURCH_READ = 'children_church:read',
    CHILDREN_CHURCH_WRITE = 'children_church:write',
    ADMIN_READ = 'admin:read',
    ADMIN_WRITE = 'admin:write',
    AUDIT_READ = 'audit:read',
    FINANCE_READ = 'finance:read',
    FINANCE_WRITE = 'finance:write',
}

export const AdminPermissionLabels: Record<AdminPermission, string> = {
    [AdminPermission.MEMBERS_READ]: 'View Members',
    [AdminPermission.MEMBERS_WRITE]: 'Manage Members',
    [AdminPermission.EVENTS_READ]: 'View Events',
    [AdminPermission.EVENTS_WRITE]: 'Manage Events',
    [AdminPermission.VENUES_READ]: 'View Venues',
    [AdminPermission.VENUES_WRITE]: 'Manage Venues',
    [AdminPermission.DEPARTMENTS_READ]: 'View Departments',
    [AdminPermission.DEPARTMENTS_WRITE]: 'Manage Departments',
    [AdminPermission.ATTENDANCE_READ]: 'View Attendance',
    [AdminPermission.LEAVE_READ]: 'View Leave Requests',
    [AdminPermission.LEAVE_WRITE]: 'Manage Leave Requests',
    [AdminPermission.CLASSES_READ]: 'View Church Classes',
    [AdminPermission.CLASSES_WRITE]: 'Manage Church Classes',
    [AdminPermission.ANNOUNCEMENTS_READ]: 'View Announcements',
    [AdminPermission.ANNOUNCEMENTS_WRITE]: 'Manage Announcements',
    [AdminPermission.NOTES_READ]: 'View Notes',
    [AdminPermission.NOTES_WRITE]: 'Manage Notes',
    [AdminPermission.DASHBOARD_READ]: 'View Dashboard',
    [AdminPermission.SUNDAY_SCHOOL_READ]: 'View Sunday School',
    [AdminPermission.SUNDAY_SCHOOL_WRITE]: 'Manage Sunday School',
    [AdminPermission.CHILDREN_CHURCH_READ]: "View Children's Church",
    [AdminPermission.CHILDREN_CHURCH_WRITE]: "Manage Children's Church",
    [AdminPermission.ADMIN_READ]: 'View Admin Users & Roles',
    [AdminPermission.ADMIN_WRITE]: 'Manage Admin Users & Roles',
    [AdminPermission.AUDIT_READ]: 'View Audit Logs',
    [AdminPermission.FINANCE_READ]: 'View Finance Records',
    [AdminPermission.FINANCE_WRITE]: 'Manage Finance Records',
};
