export enum DepartmentKeyEnum {
  SUNDAY_SCHOOL = 'SUNDAY_SCHOOL',
  CHILDREN_CHURCH = 'CHILDREN_CHURCH',
  WORSHIP = 'WORSHIP',
  USHERING = 'USHERING',
  MEDIA = 'MEDIA',
  PROTOCOL = 'PROTOCOL',
  WELFARE = 'WELFARE',
  PRAYER = 'PRAYER',
  EVANGELISM = 'EVANGELISM',
  YOUTH = 'YOUTH',
  YOUNG_ADULTS = 'YOUNG_ADULTS',
}
